#include "/Engine/Public/Platform.ush"

Texture2D InputTexture;
SamplerState InputSampler;

static const float Weights[9] =
{
	0.0625, 0.1250, 0.0625,
	0.1250, 0.2500, 0.1250,
	0.0625, 0.1250, 0.0625
};

static const float2 Offsets[9] =
{
	float2(-1.0, -1.0), float2(0.0, -1.0), float2(1.0, -1.0),
	float2(-1.0,  0.0), float2(0.0,  0.0), float2(1.0,  0.0),
	float2(-1.0,  1.0), float2(0.0,  1.0), float2(1.0,  1.0)
};

float4 MainPS(float4 SvPosition : SV_POSITION) : SV_Target0
{
	float4 Result = float4(0.0, 0.0, 0.0, 0.0);
	
	UNROLL
	for (int i = 0; i < 9; ++i)
	{
		float2 SamplePosition = SvPosition.xy + Offsets[i];
		Result += InputTexture.SampleLevel(InputSampler, SamplePosition, 0) * Weights[i];
	}

	return Result;
}
